sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cAbNRxpn1agG9Lp/RjwQZ0oiEfrXiDgyPQEufItg9eTVwt458/askg0POuiYdxNW2gxhChqsfpM7Qz24CZK2eLEliGSjk0auZBYAZq2ue0rNXPybjneqfixXvVNUsOQ1/uWwQTEaztjoHneUEbTFKqu+Nw5wDMiohSLzLdwNljAvh7Bs185XgVagLGn3JDDMA0WMBP/vMHWgmtVcfbfRwOXbveJW20qR4167dvznLW8OQHSJohrSLWku3qdQZG1YxdvsEO3iTstPoYDd+k2NDRoVePE0HgkhznCYqACzg13sYVH7/XZb2kBAEzz6m9oI9vdOEXwfS4HEnYe3EpmptLFeHcAhXPP4YNu0Nb+lwN05CC4X+x6Qlp8vjZX2mt4bBLbuOfC3mikBKsa/6qCIFkFnxnuVimG2J5w9xBYH0rSenzw9R6rp7vlpRO9a0+lZYbo6qL9S2AvfVCEEIsi9jkUyPTqXjiC7rXHe+C8PvTTYwVjIzHALbV6XuabmNVvont8lPQSagjdHuBQCRzsJTBWc+A9UBdSgQcWz5VZHosm74nrg6dfx89gAuOe+i5BycHTIRYBbcmb51xWWLMmdyQcuJYRrGnXUimKH8XJ3iBg9ixgX/xzY5OhxNBCqunTdZ0BjYQFzrmH3ZDLoj6AllbiIdbn01ixxRaNn68I4U3A=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Kent-Knowles--Quahaug_5980
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy